export const CREATE_EVENT = 'CREATE_EVENT'
export const DELETE_EVENT = 'DELETE_EVENT'
export const DELETE_ALL_EVENTS = 'DELETE_ALL_EVENTS'

export const ADD_OPREATION_LOG = 'ADD_OPREATION_LOG'
export const DELETE_ALL_OPREATION_LOGS =  'DELETE_ALL_OPREATION_LOGS'